Hanze development
HantzeWANG/software-product-sprint_2022 pull request #3
Opened 2022-06-18 21:33 UTC by HantzeWANG

week 3

2022-06-23 19:56 UTC, EvanJuV requested changes

2022-06-23 19:56 UTC, EvanJuV commented on portfolio/src/main/java/com/google/sps/servlets/HelloWorldServlet.java
> +    // response.setContentType("text/html;");
Please remove these comments.

2022-06-23 19:56 UTC, EvanJuV commented on portfolio/src/main/webapp/images.html
> +        <!-- <a href="images/pic4.jpg"><img src="images/pic4.jpg" alt="pig" width="128" height="128"/></a> -->
If you're no longer going to use these images, let's remove them instead.

2022-06-23 19:56 UTC, EvanJuV commented on portfolio/src/main/webapp/index.html
> +      <!-- <p>Click <a href="/hello">here</a> to view content generated by a servlet.</p> -->
Let's use comments to describe our code, not to hide things.

2022-06-23 19:56 UTC, EvanJuV commented on portfolio/src/main/webapp/script.js
> +    // console.log(textFromResponse.get(0));
Please also remove these comments.

2022-06-24 18:39 UTC, HantzeWANG reviewed
review changed

2022-07-01 19:30 UTC, EvanJuV approved these changes

2022-07-01 19:30 UTC, EvanJuV commented on portfolio/src/main/webapp/index.html
> +      <!-- <p>Click <a href="/hello">here</a> to view content generated by a servlet.</p> -->
You forgot to remove this comment.

2022-07-03 00:24 UTC, merged